version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "8000:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        volumes:
            - ./:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mysql:5.7.22
        environment:
            - "MYSQL_USER=formstack"
            - "MYSQL_PASSWORD=F0rmst@ck"
            - "MYSQL_ROOT_PASSWORD=F0rmst@ck"
            - "MYSQL_DATABASE=formstack"
        ports:
            - "33061:3306"
